### ISSUE TITLE
TwitterBot to automatically add Tweet to Bookmarks

### ISSUE THREAD

**Issue by FloorD** [Fidel-Willis/TwitterBot#1]
Adding a Tweet to Bookmarks is a mobile app only feature where you hit the share button under a tweet and 'Add Tweet to Bookmarks' (other options are 'Send via Direct Message' or 'Share Tweet via...'). I'd want to add tweets to bookmarks based on keywords or hashtags or maybe users they mention. 

Any hint as to how I could add this to my Python TwitterBot - thank you for the wonderful guide - Iappreciatethisisnotcustomersupport ;)

**Comment by Lucas-Kohorst** [comment]
Upon researching this I have found nothing on how to bookmark on the desktop, except for navigating to [mobile.twitter.com](mobile.twitter.com) and bookmarking from there. However, this will not work with Tweepy. 
If you want to store tweets, I think the best option would be to simply export the tweets from the keyword or hashtag and save them to a **CSV** file. If needed I could help you with this. 

You could also use **lists** on Twitter to follow a specific set of users (maybe users that you followed with the bot based on a keyword?). Tweepy offers a handy function for this.
`API.create_list(name[,** mode][, description])`
