### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OAuthHandler'

### ISSUE THREAD

**Issue by A-Sm1th** [Fidel-Willis/TwitterBot#2]
```bash
Traceback (most recent call last):
  File "TwitterBot.py", line 12, in <module>
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
AttributeError: 'module' object has no attribute 'OAuthHandler'
```

I copied the code that is written in this repo and only changed the authentication variables.

**Comment by Lucas-Kohorst** [comment]
Did you import Tweepy and sign up on Twitter for an app?

**Comment by A-Sm1th** [comment]
I did both but I just forgot to specify the path and/or move the needed file to the right folder.

But thanks for your answer 👍
